chore: Turn off automatic triggering

diff --git a/.github/workflows/bibase.yml b/.github/workflows/bibase.yml
--- a/.github/workflows/bibase.yml
+++ b/.github/workflows/bibase.yml
@@ -1,17 +1,7 @@
-name: Build Bi-base image
+name: "Build Bi-base image"
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - dev
-    paths:
-      - 'jds/p8/bi/base/Dockerfile'
-      - '.github/workflows/bibase.yml'
-
-permissions:
-  contents: write
-  actions: write
 
 env:
   ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
@@ -31,13 +21,13 @@ jobs:
           fetch-depth: 0
 
       - name: Set up Docker QEMU
-        uses: docker/setup-qemu-action@v3.4.0
+        uses: docker/setup-qemu-action@v3.6.0
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.8.0
+        uses: docker/setup-buildx-action@v3.9.0
 
       - name: Login to Aliyun Registry
-        uses: docker/login-action@v3.3.0
+        uses: docker/login-action@v3.4.0
         with:
           registry: ${{ env.ALIYUN_REGISTRY }}
           username: ${{ env.ALIYUN_REGISTRY_USER }}
@@ -45,17 +35,9 @@ jobs:
 
       - name: Bump Bi-base version
         run: |
-          CURRENT_VERSION=$(cat jds/p8/bi/base/VERSION)
-          LATEST_VERSION=$(echo "$CURRENT_VERSION" | awk -F. '{print $1"."$2"."$3+1}')
-          BASEIMG_TAG=$(cat jds/p8/bi/base/Dockerfile | grep '^ARG IMAGE_TAG=' | awk -F'=' '{print $2}' | sed 's/"//g' | sed 's/.*-//' | sed 's/[0-9.]*//g')
-
-          if [[ -z "$CURRENT_VERSION" || -z "$LATEST_VERSION" || ! "$LATEST_VERSION" =~ ^v || -z "$BASEIMG_TAG" ]]; then
-              echo "ERROR: All parameters cannot be empty!" && exit 1
-          fi
-
-          echo "$LATEST_VERSION" > jds/p8/bi/base/VERSION
-          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
-          echo "BASEIMG_TAG=${BASEIMG_TAG}" >> $GITHUB_ENV
+          CURRENT_VERSION=$(awk -F"'" '/# BASE_VER/{print $2}' jds/p8/bi/base/Dockerfile)
+          [ -z "$CURRENT_VERSION" ] && { echo "ERROR: Parameters cannot be empty!"; exit 1; }
+          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
 
       - name: Build and push Bi-base image
         uses: docker/build-push-action@v6.11.0
@@ -63,10 +45,5 @@ jobs:
           context: "{{defaultContext}}:jds/p8/bi/base"
           file: Dockerfile
           push: true
-          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/bi-base:${{ env.LATEST_VERSION }}-${{ env.BASEIMG_TAG }}
-          platforms: linux/amd64,linux/arm64
-
-      - name: Commit version update
-        uses: stefanzweifel/git-auto-commit-action@v5.1.0
-        with:
-          commit_message: "chore: bump version by Github Actions"
+          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/bi-base:${{ env.CURRENT_VERSION }}
+          platforms: linux/amd64, linux/arm64/v8
