fix: optimize build process with clearer logic

diff --git a/.github/workflows/bibase.yml b/.github/workflows/bibase.yml
--- a/.github/workflows/bibase.yml
+++ b/.github/workflows/bibase.yml
@@ -5,9 +5,13 @@ on:
     branches:
       - dev
     paths:
-      - 'jds/p8/bi/Dockerfile_base'
       - '.github/workflows/bibase.yml'
+      - 'jds/p8/bi/Dockerfile_base'
   workflow_dispatch:
+
+permissions:
+  contents: write
+  actions: write
 
 env:
   ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
@@ -34,12 +38,23 @@ jobs:
           password: ${{ env.ALIYUN_REGISTRY_PASSWORD }}
 
       - name: Set tag
-        id: date
         run: |
-          BUILD_DATE=$(date +'%Y.%m.%d')
-          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
-          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
-          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
+          VERSION=$(cat jds/p8/bi/BASE_VERSION)
+          echo "current version is $VERSION"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          NEW_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
+          echo "new version is $NEW_VERSION"
+          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+          if [[ ! "$NEW_VERSION" =~ ^v ]]; then
+              echo "ERROR: NEW_VERSION does not start with, exiting!"
+              exit 1
+          fi
+          echo "$NEW_VERSION" > jds/p8/bi/BASE_VERSION
+          echo "BASE_IMG_TAG=$(cat jds/p8/bi/Dockerfile_base | grep '^ARG PYTHON_IMAGE_TAG=' | awk -F'=' '{print $2}' | sed 's/.*-//' | sed 's/[0-9.]*//g')" >> $GITHUB_ENV
+          if [[ -z $BASE_IMG_TAG ]]; then
+            echo "ERROR: variable BASE_IMG_TAG not defined, exiting!"
+            exit 1
+          fi
 
       - name: Build and push Bi baseimage
         uses: docker/build-push-action@v6.11.0
@@ -47,5 +62,10 @@ jobs:
           context: "{{defaultContext}}:jds/p8/bi"
           file: Dockerfile_base
           push: true
-          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/bi-base:${{ env.BUILD_DATE }}-${{ env.SHORT_SHA }}
-          platforms: linux/amd64
+          tags: ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/bi-base:${{ env.VERSION }}-${{ env.BASE_IMG_TAG }}
+          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
+
+      - name: Commit version update
+        uses: stefanzweifel/git-auto-commit-action@v5.1.0
+        with:
+          commit_message: "chore: bi baseimage bump version"
